
// Sample product data
export const products = [
    {
      id: 1,
      name: "Arduino Uno R4 Wifi",
      price: 7.99,
      originalPrice: 13.0,
      rating: 5,
      image: "https://i.ibb.co/kgtX0Nq7/Arduino-uno.webp",
      isNew: true,
      discount: 50,
      category: "Accessories",
      description:
        "Super-soft cushion cover in off-white with a tactile pattern that enhances the different tones in the pile and base.",
    },
    {
      id: 2,
      name: "Arduino Giga",
      price: 299.99,
      originalPrice: 599.99,
      rating: 5,
      image: "https://i.ibb.co/7NVh68vc/arduino-giga.webp",
      isNew: true,
      discount: 50,
      category: "Living Room",
      description: "Premium comfort with elegant design",
    },
    {
      id: 3,
      name: "Arduino Nano Headers",
      price: 59.99,
      rating: 5,
      image: "https://i.ibb.co/CKn6hkxV/arduino-nano-with-headers.webp",
      isNew: true,
      discount: 50,
      category: "Lighting",
      description: "Modern lighting solution for your space",
    },
    {
      id: 4,
      name: "Arduino Uno R4 Wifi",
      price: 89.99,
      rating: 5,
      image: "https://i.ibb.co/kgtX0Nq7/Arduino-uno.webp",
      isNew: true,
      discount: 50,
      category: "Storage",
      description: "Versatile storage solution",
    },
    {
      id: 5,
      name: "Arduino Giga",
      price: 19.99,
      rating: 5,
      image: "https://i.ibb.co/7NVh68vc/arduino-giga.webp",
      isNew: true,
      discount: 50,
      category: "Living Room",
      description: "Sleek and functional side table",
    },
    {
      id: 6,
      name: "Arduino Nano Headers",
      price: 39.99,
      rating: 5,
      image: "https://i.ibb.co/CKn6hkxV/arduino-nano-with-headers.webp",
      isNew: true,
      discount: 50,
      category: "Lighting",
      description: "Statement lighting piece",
    },
    {
      id: 7,
      name: "Arduino Uno R4 Wifi",
      price: 5.99,
      rating: 5,
      image: "https://i.ibb.co/kgtX0Nq7/Arduino-uno.webp",
      isNew: true,
      discount: 50,
      category: "Accessories",
      description: "Soft and cozy accent pillow",
    },
    {
      id: 8,
      name: "Arduino Giga",
      price: 39.99,
      rating: 5,
      image: "https://i.ibb.co/7NVh68vc/arduino-giga.webp",
      isNew: true,
      discount: 50,
      category: "Lighting",
      description: "Contemporary desk lighting",
    },
    {
      id: 9,
      name: "Arduino Nano Headers",
      price: 9.99,
      rating: 5,
      image: "https://i.ibb.co/CKn6hkxV/arduino-nano-with-headers.webp",
      isNew: true,
      discount: 50,
      category: "Storage",
      description: "Eco-friendly storage solution",
    },
  ]
  
  